# Generated by Django 2.0.2 on 2018-03-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, null=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('address2', models.CharField(max_length=10, null=True)),
                ('town', models.CharField(max_length=25, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
