# Generated by Django 2.0.2 on 2018-03-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, null=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('size', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
