# Generated by Django 2.0.2 on 2018-03-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180317_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='first_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='pizza',
            field=models.CharField(max_length=100, null=True, verbose_name='Pizzas'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='size',
            field=models.CharField(choices=[('30cm', '30 CM'), ('40cm', '40 CM'), ('50cm', '50 CM'), ('55cm', '55 CM')], default='30cm', max_length=6),
        ),
    ]
